services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/php/Dockerfile
    container_name: cognivia_backend      
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - cognivia_network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: cognivia_nginx
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cognivia_network
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: cognivia_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3307:3306"
    volumes:
      - cognivia_mysql_data:/var/lib/mysql
    networks:
      - cognivia_network

networks:
  cognivia_network:
    driver: bridge

volumes:
  cognivia_mysql_data: