services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/php/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: cognivia_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    network_mode: host
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    container_name: cognivia_frontend
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:                        
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=3001
      - FAST_REFRESH=false
      - HOST=0.0.0.0
      - PORT=3001
    networks:
      - cognivia_network
  nginx:
    image: nginx:alpine
    container_name: cognivia_nginx
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cognivia_network
    depends_on:
      - backend
      - frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:8.0
    container_name: cognivia_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - cognivia_mysql_data:/var/lib/mysql
    networks:
      - cognivia_network

networks:
  cognivia_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.enable_icc: "true"

volumes:
  cognivia_mysql_data:
